version: '3.1'

services:
  anhtaidang-cloud-server:
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
     - ./docker-deploy:/app
    networks:
      - app-network

networks:
  app-network:
    name: ${ENV_DEPLOY}-${APP_NAME}-app-network
    driver: bridge
    ipam:
      driver: default
