version: '3.1'

name: anhtaidang-cloud-server

services:
  app:
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    name: ${ENV_DEPLOY}-${APP_NAME}-app-network
    driver: bridge
    ipam:
      driver: default
