version: '3.1'

services:
  postgres:
    image: postgres:10
    container_name: postgres_dummy_api
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anhtaidang
      POSTGRES_DB: cloudverse
    volumes:
      - my_postgres_data:/var/lib/postgresql/data

volumes:
  my_postgres_data:
